In [161]:
import pandas as pd
import numpy as np

pd.set_option("mode.copy_on_write", True)

In [162]:
# List of columns to select
selected_columns = ["title", "tags", "categoryId", "description"]

df = pd.read_csv("US_youtube_trending_data.csv", usecols=selected_columns)
df.head()

,title,categoryId,tags,description
0,I ASKED HER TO BE MY GIRLFRIEND...,22,brawadis|prank|basketball|skits|ghost|funny vi...,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...
1,Apex Legends | Stories from the Outlands – “Th...,20,Apex Legends|Apex Legends characters|new Apex ...,"While running her own modding shop, Ramya Pare..."
2,I left youtube for a month and THIS is what ha...,24,jacksepticeye|funny|funny meme|memes|jacksepti...,I left youtube for a month and this is what ha...
3,XXL 2020 Freshman Class Revealed - Official An...,10,xxl freshman|xxl freshmen|2020 xxl freshman|20...,Subscribe to XXL → http://bit.ly/subscribe-xxl...
4,Ultimate DIY Home Movie Theater for The LaBran...,26,The LaBrant Family|DIY|Interior Design|Makeove...,Transforming The LaBrant Family's empty white ...

In [163]:
# Count the occurrences of each categoryId
category_counts = df["categoryId"].value_counts()

# Get the top four most frequent categoryIds
top_four_categories = category_counts.head(4)

# Display the top four categories
print(top_four_categories)

categoryId
24    47323
20    46998
10    39136
17    27411
Name: count, dtype: int64

In [164]:
# List of selected category IDs
selected_category_id = [10, 17, 20, 24]
df = df.loc[df["categoryId"].isin(selected_category_id)]

In [165]:
df.head()

,title,categoryId,tags,description
1,Apex Legends | Stories from the Outlands – “Th...,20,Apex Legends|Apex Legends characters|new Apex ...,"While running her own modding shop, Ramya Pare..."
2,I left youtube for a month and THIS is what ha...,24,jacksepticeye|funny|funny meme|memes|jacksepti...,I left youtube for a month and this is what ha...
3,XXL 2020 Freshman Class Revealed - Official An...,10,xxl freshman|xxl freshmen|2020 xxl freshman|20...,Subscribe to XXL → http://bit.ly/subscribe-xxl...
5,I Haven't Been Honest About My Injury.. Here's...,24,Professor injury|professor achilles|professor ...,Subscribe To My Channel - https://www.youtube....
8,SURPRISING MY DAD WITH HIS DREAM TRUCK!! | Lou...,24,surprising|dad|father|papa|with|dream|car|truc...,"Since I was little, i've had these goals for m..."

In [166]:
df

,title,categoryId,tags,description
1,Apex Legends | Stories from the Outlands – “Th...,20,Apex Legends|Apex Legends characters|new Apex ...,"While running her own modding shop, Ramya Pare..."
2,I left youtube for a month and THIS is what ha...,24,jacksepticeye|funny|funny meme|memes|jacksepti...,I left youtube for a month and this is what ha...
3,XXL 2020 Freshman Class Revealed - Official An...,10,xxl freshman|xxl freshmen|2020 xxl freshman|20...,Subscribe to XXL → http://bit.ly/subscribe-xxl...
5,I Haven't Been Honest About My Injury.. Here's...,24,Professor injury|professor achilles|professor ...,Subscribe To My Channel - https://www.youtube....
8,SURPRISING MY DAD WITH HIS DREAM TRUCK!! | Lou...,24,surprising|dad|father|papa|with|dream|car|truc...,"Since I was little, i've had these goals for m..."
...,...,...,...,...
237376,Coach Pierce and Aidan O'Connell Postgame Pres...,17,raiders|las vegas raiders|livestream|live|pres...,Interim Head Coach Antonio Pierce and QB Aidan...
237377,Mauga | New Hero Gameplay Trailer | Overwatch 2,20,Overwatch 2|Overwatch,Overwatch 2’s latest Tank Hero Mauga is chargi...
237379,Pauly Shore Proposes to Drew Barrymore | The D...,24,drew barrymore|drew barrymore show|drew barrym...,Pauly Shore opens up to Drew Barrymore about s...
237380,Here’s How Much Snow You’ll Get This Year…,24,weather|weather forecasting|forecasting|foreca...,Get your Y'all-O-Meter 2.0 here: https://shopr...
237383,SEAN EVANS | CHICKEN SHOP DATE,24,[None],Amelia meets Hot Ones host Sean Evans for a da...

In [167]:
df = pd.read_csv("US_youtube_trending_data.csv", nrows=200)
df.head()

,video_id,title,publishedAt,channelId,channelTitle,categoryId,trending_date,tags,view_count,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,description
0,3C66w5Z0ixs,I ASKED HER TO BE MY GIRLFRIEND...,2020-08-11T19:20:14Z,UCvtRTOMP2TqYqu51xNrqAzg,Brawadis,22,2020-08-12T00:00:00Z,brawadis|prank|basketball|skits|ghost|funny vi...,1514614,156908,5855,35313,https://i.ytimg.com/vi/3C66w5Z0ixs/default.jpg,False,False,SUBSCRIBE to BRAWADIS ▶ http://bit.ly/Subscrib...
1,M9Pmf9AB4Mo,Apex Legends | Stories from the Outlands – “Th...,2020-08-11T17:00:10Z,UC0ZV6M2THA81QT9hrVWJG3A,Apex Legends,20,2020-08-12T00:00:00Z,Apex Legends|Apex Legends characters|new Apex ...,2381688,146739,2794,16549,https://i.ytimg.com/vi/M9Pmf9AB4Mo/default.jpg,False,False,"While running her own modding shop, Ramya Pare..."
2,J78aPJ3VyNs,I left youtube for a month and THIS is what ha...,2020-08-11T16:34:06Z,UCYzPXprvl5Y-Sf0g4vX-m6g,jacksepticeye,24,2020-08-12T00:00:00Z,jacksepticeye|funny|funny meme|memes|jacksepti...,2038853,353787,2628,40221,https://i.ytimg.com/vi/J78aPJ3VyNs/default.jpg,False,False,I left youtube for a month and this is what ha...
3,kXLn3HkpjaA,XXL 2020 Freshman Class Revealed - Official An...,2020-08-11T16:38:55Z,UCbg_UMjlHJg_19SZckaKajg,XXL,10,2020-08-12T00:00:00Z,xxl freshman|xxl freshmen|2020 xxl freshman|20...,496771,23251,1856,7647,https://i.ytimg.com/vi/kXLn3HkpjaA/default.jpg,False,False,Subscribe to XXL → http://bit.ly/subscribe-xxl...
4,VIUo6yapDbc,Ultimate DIY Home Movie Theater for The LaBran...,2020-08-11T15:10:05Z,UCDVPcEbVLQgLZX0Rt6jo34A,Mr. Kate,26,2020-08-12T00:00:00Z,The LaBrant Family|DIY|Interior Design|Makeove...,1123889,45802,964,2196,https://i.ytimg.com/vi/VIUo6yapDbc/default.jpg,False,False,Transforming The LaBrant Family's empty white ...

In [168]:
# List of columns to select
selected_columns = ["title", "tags", "categoryId", "description"]

# List of selected category IDs
selected_category_id = [10, 17, 20, 24]

# Create an empty list to store filtered dataframes
filtered_data_list = []

# Set a chunk size
chunk_size = 150000

# Use the `read_csv` function with `chunksize` and `usecols` parameters
for chunk in pd.read_csv(
    "US_youtube_trending_data.csv",
    chunksize=chunk_size,
    usecols=selected_columns,
    low_memory=False,
):
    # Filter the chunk for the selected categories
    filtered_chunk = chunk[chunk["categoryId"].isin(selected_category_id)]
    # Append the filtered chunk to the list
    filtered_data_list.append(filtered_chunk)

# Combine all the filtered chunks into a single dataframe
final_df = pd.concat(filtered_data_list, ignore_index=True)

In [169]:
final_df

,title,categoryId,tags,description
0,Apex Legends | Stories from the Outlands – “Th...,20,Apex Legends|Apex Legends characters|new Apex ...,"While running her own modding shop, Ramya Pare..."
1,I left youtube for a month and THIS is what ha...,24,jacksepticeye|funny|funny meme|memes|jacksepti...,I left youtube for a month and this is what ha...
2,XXL 2020 Freshman Class Revealed - Official An...,10,xxl freshman|xxl freshmen|2020 xxl freshman|20...,Subscribe to XXL → http://bit.ly/subscribe-xxl...
3,I Haven't Been Honest About My Injury.. Here's...,24,Professor injury|professor achilles|professor ...,Subscribe To My Channel - https://www.youtube....
4,SURPRISING MY DAD WITH HIS DREAM TRUCK!! | Lou...,24,surprising|dad|father|papa|with|dream|car|truc...,"Since I was little, i've had these goals for m..."
...,...,...,...,...
160863,Coach Pierce and Aidan O'Connell Postgame Pres...,17,raiders|las vegas raiders|livestream|live|pres...,Interim Head Coach Antonio Pierce and QB Aidan...
160864,Mauga | New Hero Gameplay Trailer | Overwatch 2,20,Overwatch 2|Overwatch,Overwatch 2’s latest Tank Hero Mauga is chargi...
160865,Pauly Shore Proposes to Drew Barrymore | The D...,24,drew barrymore|drew barrymore show|drew barrym...,Pauly Shore opens up to Drew Barrymore about s...
160866,Here’s How Much Snow You’ll Get This Year…,24,weather|weather forecasting|forecasting|foreca...,Get your Y'all-O-Meter 2.0 here: https://shopr...
160867,SEAN EVANS | CHICKEN SHOP DATE,24,[None],Amelia meets Hot Ones host Sean Evans for a da...

In [170]:
final_df.to_parquet("final_youtube_US.parquet")

In [171]:
import pandas as pd

# List of columns to select
selected_columns = ["title", "tags", "categoryId", "description"]

# Dictionary to count categoryId occurrences
category_count = {}

# Set a chunk size
chunk_size = 150000

# First Pass: Count occurrences of each categoryId
for chunk in pd.read_csv(
    "US_youtube_trending_data.csv",
    chunksize=chunk_size,
    usecols=["categoryId"],
    low_memory=False,
):
    for categoryId in chunk["categoryId"]:
        if categoryId in category_count:
            category_count[categoryId] += 1
        else:
            category_count[categoryId] = 1

# Identify the top 4 most popular categoryIds
top_categories = sorted(category_count, key=category_count.get, reverse=True)[:4]

top_categories

[24, 20, 10, 17]

In [172]:
# Create an empty list to store filtered dataframes
filtered_data_list_2 = []

# Second Pass: Filter the data
for chunk in pd.read_csv(
    "US_youtube_trending_data.csv",
    chunksize=chunk_size,
    usecols=selected_columns,
    low_memory=False,
):
    # Filter the chunk for the top categories
    filtered_chunk = chunk[chunk["categoryId"].isin(top_categories)]
    # Append the filtered chunk to the list
    filtered_data_list_2.append(filtered_chunk)

# Combine all the filtered chunks into a single dataframe
final_df_2 = pd.concat(filtered_data_list_2, ignore_index=True)

final_df_2

,title,categoryId,tags,description
0,Apex Legends | Stories from the Outlands – “Th...,20,Apex Legends|Apex Legends characters|new Apex ...,"While running her own modding shop, Ramya Pare..."
1,I left youtube for a month and THIS is what ha...,24,jacksepticeye|funny|funny meme|memes|jacksepti...,I left youtube for a month and this is what ha...
2,XXL 2020 Freshman Class Revealed - Official An...,10,xxl freshman|xxl freshmen|2020 xxl freshman|20...,Subscribe to XXL → http://bit.ly/subscribe-xxl...
3,I Haven't Been Honest About My Injury.. Here's...,24,Professor injury|professor achilles|professor ...,Subscribe To My Channel - https://www.youtube....
4,SURPRISING MY DAD WITH HIS DREAM TRUCK!! | Lou...,24,surprising|dad|father|papa|with|dream|car|truc...,"Since I was little, i've had these goals for m..."
...,...,...,...,...
160863,Coach Pierce and Aidan O'Connell Postgame Pres...,17,raiders|las vegas raiders|livestream|live|pres...,Interim Head Coach Antonio Pierce and QB Aidan...
160864,Mauga | New Hero Gameplay Trailer | Overwatch 2,20,Overwatch 2|Overwatch,Overwatch 2’s latest Tank Hero Mauga is chargi...
160865,Pauly Shore Proposes to Drew Barrymore | The D...,24,drew barrymore|drew barrymore show|drew barrym...,Pauly Shore opens up to Drew Barrymore about s...
160866,Here’s How Much Snow You’ll Get This Year…,24,weather|weather forecasting|forecasting|foreca...,Get your Y'all-O-Meter 2.0 here: https://shopr...
160867,SEAN EVANS | CHICKEN SHOP DATE,24,[None],Amelia meets Hot Ones host Sean Evans for a da...

In [173]:
final_df["title"].sample(20)

123713    I Cheated Using a PRO BUILDER in Minecraft Bui...
101131              Race Highlights | 2022 Dutch Grand Prix
20287         Joey Bada$$ - Let It Breathe (Official Video)
24612     Chaos and Creatures | Ep. 22 | Minecraft X Lif...
47609     I Survived 100 Days as an EVOKER in Hardcore M...
139294                        I Cooked In The Arctic Circle
7770      Roboy - 1017 Loaded (feat. Gucci Mane, Big Sca...
18077     What Happened to EVERY Heisman Winner Since 20...
32899                               Team RAR Goes to PROM!!
131274                       This New Spy Game is Hilarious
134656                Soooo… We Bought an Abandoned Resort…
148129                      Baldur's Gate 3: Launch Trailer
72941     Nathan Chen accepts his very first gold medal ...
90932      Conan Gray - Best Friend  (Official Lyric Video)
77767                                     what happens now?
126775        Chris Rock addresses infamous Will Smith slap
157672    NRL 2023 | PNG PM’s XIII v AUS PM’s XIII | Mat...
51034     Can The World Record Paper Airplane Fly The Le...
2267      Ronaldo Helps Clix and Unknown End Their Beef ...
97649     Back To School Prepare With Me 2022: 1st Day O...
Name: title, dtype: object

In [174]:
final_df["tags"].sample(20)

113606    clash of clans|COC|Clash of Clans Gameplay|Cla...
86562                                                [None]
65499     Minecraft|hermitcraft|hermitcraft season 8|her...
98108     unbreakable box|never ending|Dangie bros|team ...
78798     Nicki Minaj|ニッキーミナージュ|ニッキー・ミナージュ|Fivio Foreign...
119914    minecraft|maizen|Carty|Smirky|Omziscool|Kory|C...
23293              slowthai|Skepta|CANCELLED|Method|Hip|Hop
80045     artisthbtl|a boogie wit da hoodie|a boogie|hoo...
63094     Project L|ProjectL|fighting game|fight|fgc|Rio...
46549     Among Us|Imposter|Among Us Mod|Zudoia|Zud|Amon...
9283      The Sims 4|The Sims 4 Trailer|The Sims 4 Gamep...
136920    vh1|rupaul|rupaul's drag race|drag race|the pi...
82584     roblox|red ninja|redninja|sonic|sonic speed si...
13834     Teenage Dream|Teenage|Dream|Kidd G Teenage Dre...
102069    mmg|mmg live|mmg livestream|mmg nfl live|mmg m...
27410     ufc|dana white|boxing|mike tyson|Conor McGrego...
13770     Amber|amber vtuber|genshi|genshi game|genshi i...
139057    clash of clans|COC|Clash of Clans Gameplay|Cla...
49873           call of duty|cod|activision|vanguard|reveal
11612     Lil|Uzi|Vert|Lil Uzi Vert|Money Longer|LUV|Fut...
Name: tags, dtype: object

In [175]:
import re


def clean_and_tokenize(tag_string):
    # Remove non-alphanumeric characters and convert to lowercase
    cleaned_string = re.sub(r"[^a-zA-Z0-9\s|]", "", tag_string.lower())

    # Tokenize the string into words
    tokens = cleaned_string.split("|")

    # Remove leading and trailing whitespaces from each token
    tokens = [token.strip() for token in tokens]

    return tokens

In [176]:
# Apply the cleaning and tokenization function to the 'Tags' column
final_df["tokenized_tags"] = final_df["tags"].apply(clean_and_tokenize)

# Display the DataFrame with the tokenized tags
final_df["tokenized_tags"]

0         [apex legends, apex legends characters, new ap...
1         [jacksepticeye, funny, funny meme, memes, jack...
2         [xxl freshman, xxl freshmen, 2020 xxl freshman...
3         [professor injury, professor achilles, profess...
4         [surprising, dad, father, papa, with, dream, c...
                                ...
160863    [raiders, las vegas raiders, livestream, live,...
160864                             [overwatch 2, overwatch]
160865    [drew barrymore, drew barrymore show, drew bar...
160866    [weather, weather forecasting, forecasting, fo...
160867                                               [none]
Name: tokenized_tags, Length: 160868, dtype: object

In [177]:
final_df

,title,categoryId,tags,description,tokenized_tags
0,Apex Legends | Stories from the Outlands – “Th...,20,Apex Legends|Apex Legends characters|new Apex ...,"While running her own modding shop, Ramya Pare...","[apex legends, apex legends characters, new ap..."
1,I left youtube for a month and THIS is what ha...,24,jacksepticeye|funny|funny meme|memes|jacksepti...,I left youtube for a month and this is what ha...,"[jacksepticeye, funny, funny meme, memes, jack..."
2,XXL 2020 Freshman Class Revealed - Official An...,10,xxl freshman|xxl freshmen|2020 xxl freshman|20...,Subscribe to XXL → http://bit.ly/subscribe-xxl...,"[xxl freshman, xxl freshmen, 2020 xxl freshman..."
3,I Haven't Been Honest About My Injury.. Here's...,24,Professor injury|professor achilles|professor ...,Subscribe To My Channel - https://www.youtube....,"[professor injury, professor achilles, profess..."
4,SURPRISING MY DAD WITH HIS DREAM TRUCK!! | Lou...,24,surprising|dad|father|papa|with|dream|car|truc...,"Since I was little, i've had these goals for m...","[surprising, dad, father, papa, with, dream, c..."
...,...,...,...,...,...
160863,Coach Pierce and Aidan O'Connell Postgame Pres...,17,raiders|las vegas raiders|livestream|live|pres...,Interim Head Coach Antonio Pierce and QB Aidan...,"[raiders, las vegas raiders, livestream, live,..."
160864,Mauga | New Hero Gameplay Trailer | Overwatch 2,20,Overwatch 2|Overwatch,Overwatch 2’s latest Tank Hero Mauga is chargi...,"[overwatch 2, overwatch]"
160865,Pauly Shore Proposes to Drew Barrymore | The D...,24,drew barrymore|drew barrymore show|drew barrym...,Pauly Shore opens up to Drew Barrymore about s...,"[drew barrymore, drew barrymore show, drew bar..."
160866,Here’s How Much Snow You’ll Get This Year…,24,weather|weather forecasting|forecasting|foreca...,Get your Y'all-O-Meter 2.0 here: https://shopr...,"[weather, weather forecasting, forecasting, fo..."
160867,SEAN EVANS | CHICKEN SHOP DATE,24,[None],Amelia meets Hot Ones host Sean Evans for a da...,[none]

In [178]:
# Select only 'categoryId' and 'tokenized_tags' columns
new_df = final_df[["categoryId", "tokenized_tags"]]

# Display the new DataFrame
new_df

        categoryId                                     tokenized_tags
0               20  [apex legends, apex legends characters, new ap...
1               24  [jacksepticeye, funny, funny meme, memes, jack...
2               10  [xxl freshman, xxl freshmen, 2020 xxl freshman...
3               24  [professor injury, professor achilles, profess...
4               24  [surprising, dad, father, papa, with, dream, c...
...            ...                                                ...
160863          17  [raiders, las vegas raiders, livestream, live,...
160864          20                           [overwatch 2, overwatch]
160865          24  [drew barrymore, drew barrymore show, drew bar...
160866          24  [weather, weather forecasting, forecasting, fo...
160867          24                                             [none]

[160868 rows x 2 columns]

In [179]:
# Convert lists to strings, replace commas with spaces, and optionally convert back to lists
new_df["tokenized_tags"] = new_df["tokenized_tags"].apply(
    lambda x: " ".join(x) if isinstance(x, list) else x
)

# Display the updated DataFrame
new_df

        categoryId                                     tokenized_tags
0               20  apex legends apex legends characters new apex ...
1               24  jacksepticeye funny funny meme memes jacksepti...
2               10  xxl freshman xxl freshmen 2020 xxl freshman 20...
3               24  professor injury professor achilles professor ...
4               24  surprising dad father papa with dream car truc...
...            ...                                                ...
160863          17  raiders las vegas raiders livestream live pres...
160864          20                              overwatch 2 overwatch
160865          24  drew barrymore drew barrymore show drew barrym...
160866          24  weather weather forecasting forecasting foreca...
160867          24                                               none

[160868 rows x 2 columns]

In [180]:
# Filter the DataFrame for each category ID
df_category_10 = new_df[new_df["categoryId"] == 10]
df_category_17 = new_df[new_df["categoryId"] == 17]
df_category_20 = new_df[new_df["categoryId"] == 20]
df_category_24 = new_df[new_df["categoryId"] == 24]

In [181]:
df_category_10.head()

    categoryId                                     tokenized_tags
2           10  xxl freshman xxl freshmen 2020 xxl freshman 20...
5           10  vengo de nada aleman ovi big soto trap ovi nat...
7           10  lil yachty lil boat 3 future lil yachty pardon...
9           10  jyp entertainment jyp itzy  itzy video itzy ye...
13          10  iann dior sadboy dior iann dior internet money...

In [182]:
# Create a big list containing lists of tokens from each row in 'tokenized_tags' for category 10
big_list_of_tokenized_tags_10 = [
    row.split(" ") for row in df_category_10["tokenized_tags"]
]

# Print the big list
print(big_list_of_tokenized_tags_10[:3])

[['xxl', 'freshman', 'xxl', 'freshmen', '2020', 'xxl', 'freshman', '2020', 'freshman', '2020', 'freshmen', 'xxl', 'freshman', 'class', '2020', 'xxl', 'freshman', 'class', 'nle', 'choppa', 'polo', 'g', 'chika', 'baby', 'keem', 'mulatto', 'jack', 'harlow', 'rod', 'wave', 'lil', 'tjay', 'calboy', 'fivio', 'foreign', 'lil', 'keed', '24kgoldn', 'rapper', 'rap', 'hiphop', 'music'], ['vengo', 'de', 'nada', 'aleman', 'ovi', 'big', 'soto', 'trap', 'ovi', 'natanel', 'cano', 'big', 'soto', 'aleman', 'nata', 'aleman', 'ovi', 'vengo', 'de', 'nada', 'natanael', 'cano', 'vengo', 'de', 'nada', 'aleman', 'vengo', 'de', 'nada', 'big', 'soto', 'vengo', 'de', 'nada', 'natanael', 'cano', 'nata', 'legado', '7', 'herencia', 'de', 'patrones', 'el', 'de', 'la', 'guitarra', 'grupo', 'codiciado', 'alta', 'consigna', 'junior', 'h', 'cosas', 'de', 'la', 'clica', 'pacas', 'verdes', 'el', 'drip', 'corridos', 'tumbados', 'jimmy', 'humilde', 'rancho', 'humilde', 'rancho', 'corridos', 'corridos', 'verdes', 'regional', 'urbano', 'clika', 'smo', 'regional', 'mexicano', 'banda'], ['lil', 'yachty', 'lil', 'boat', '3', 'future', 'lil', 'yachty', 'pardon', 'me', 'future', 'pardon', 'me', 'lil', 'yachty', 'lil', 'yachty', 'future', 'pardon', 'me']]

In [183]:
# Specify the file path
file_path = "category10.txt"

# Open the file in write mode
with open(file_path, "w") as file:
    # Iterate through the list of lists
    for sublist in big_list_of_tokenized_tags_10:
        # Convert each element to a string and join them with a delimiter (e.g., comma)
        line = ",".join(map(str, sublist))

        # Write the line to the file
        file.write(line + "\n")

In [184]:
df_category_17.head()

    categoryId                                     tokenized_tags
17          17  fox fox sports fs1 fox sports 1 undisputed ski...
18          17  bleacher report br nba giannis giannis antetok...
21          17  nba g league basketball game0021901300 jump sh...
30          17  first take damian lillard paul george patrick ...
32          17  nba g league basketball game0021901296 jump sh...

In [185]:
# Create a big list containing lists of tokens from each row in 'tokenized_tags' for category 17
big_list_of_tokenized_tags_17 = [
    row.split(" ") for row in df_category_17["tokenized_tags"]
]

# Print the big list
print(big_list_of_tokenized_tags_17[:3])

[['fox', 'fox', 'sports', 'fs1', 'fox', 'sports', '1', 'undisputed', 'skip', 'bayless', 'shannon', 'sharpe', 'skip', 'and', 'shannon', 'fs1', 'undisputed', 'skip', 'bayless', 'shannon', 'sharpe', 'sports', 'news', 'los', 'angeles', 'lakers', 'nba', 'basketball', 'bubble', 'lebron', 'james', 'anthony', 'davis', 'ad', 'kyle', 'kuzma', 'denver', 'nuggets', 'kylekuzma', 'alexander', 'los', 'angeles', 'lakers', 'lebron', 'vs', 'lakers', 'lebronjames', 'raymone', 'national', 'basketball', 'association', 'denver', 'nuggets', 'kyle', 'kuzma', 'anthonydavis', 'anthony', 'marshon', 'davis', 'lebron', 'vs', 'kyle', 'kuzma'], ['bleacher', 'report', 'br', 'nba', 'giannis', 'giannis', 'antetokounmpo', 'giannis', 'fight', 'giannis', 'headbutt', 'giannis', 'moritz', 'wagner', 'moritz', 'wagner', 'giannis', 'ejection', 'giannis', 'nba', 'fight', 'giannis', 'thrown', 'out', 'giannis', 'bucks', 'giannis', 'nba', 'bubble', 'milwaukee', 'bucks', 'giannis', 'mo', 'wagner', 'headbutt', 'washington', 'wizards', 'nba', 'bubble', 'nba', 'seeding', 'games'], ['nba', 'g', 'league', 'basketball', 'game0021901300', 'jump', 'shot', 'steal', 'rebound', 'assist', 'pass', '201920', 'season', 'nba', 'season', '201920', 'disney', 'nba', 'restart', 'whole', 'new', 'game', 'highlight', 'highlights', 'full', 'game', 'highlights', 'full', 'game', 'recap', 'dallas', 'dallas', 'mavericks', 'trail', 'blazers', 'portland', 'portland', 'trail', 'blazers', 'damian', 'lillard', 'dame', 'time', 'dame', 'carmelo', 'anthony', 'melo']]

In [186]:
# Specify the file path
file_path = "category17.txt"

# Open the file in write mode
with open(file_path, "w") as file:
    # Iterate through the list of lists
    for sublist in big_list_of_tokenized_tags_17:
        # Convert each element to a string and join them with a delimiter (e.g., comma)
        line = ",".join(map(str, sublist))

        # Write the line to the file
        file.write(line + "\n")

In [187]:
df_category_20.head()

    categoryId                                     tokenized_tags
0           20  apex legends apex legends characters new apex ...
6           20  r6 r6s siege new siege new operators new ops g...
35          20  fifa fifa 21 fifa21 fifa 21 trailer fifa 21 ne...
40          20                  agent 00 cashnasty 1v1 basketball
50          20  minecraft minecraft theory minecraft diamonds ...

In [188]:
# Create a big list containing lists of tokens from each row in 'tokenized_tags' for category 20
big_list_of_tokenized_tags_20 = [
    row.split(" ") for row in df_category_20["tokenized_tags"]
]

# Print the big list
print(big_list_of_tokenized_tags_20[:3])

[['apex', 'legends', 'apex', 'legends', 'characters', 'new', 'apex', 'legend', 'apex', 'legends', 'rampart', 'apex', 'legends', 'season', '6', 'apex', 'legends', 'boosted', 'battle', 'pass', 'season', '6', 'battle', 'pass', 'apex', 'legends', 'new', 'season', 'apex', 'legends', 'game', 'respawn', 'apex', 'legends', 'battle', 'royale', 'game', 'battle', 'royale', 'battle', 'royale', 'shooter', 'apex', 'games', 'squad', 'play', 'multiplayer', 'shooter', 'apex', 'legends', 'ps4', 'apex', 'legends', 'xbox', 'apex', 'legends', 'pc', 'apex', 'legends', 'origin', 'respawn', 'entertainment', 'electronic', 'arts', 'titanfall', '2', 'fun', 'battle', 'royale'], ['r6', 'r6s', 'siege', 'new', 'siege', 'new', 'operators', 'new', 'ops', 'gameplay', 'rainbow', 'six', 'new', 'operators', 'r6s', 'new', 'operation', 'ubisoft', 'ubi', 'operation', 'shadow', 'legacy', 'shadow', 'legacy', 'r6s', 'shadow', 'legacy', 'rainbow', '6', 'shadow', 'legacy', 'year', '5', 'season', '3', 'y5s3', 'sam', 'fisher', 'splinter', 'cell', 'rainbow', '6', 'sam', 'fisher', 'zero', 'r6', 'zero', 'r6s', 'zero', 'rainbow', '6', 'zero'], ['fifa', 'fifa', '21', 'fifa21', 'fifa', '21', 'trailer', 'fifa', '21', 'news', 'fifa', '21', 'ps4', 'fifa', '21', 'ps4', 'gameplay', 'fifa', '21', 'xbox', 'one', 'fifa', '21', 'gameplay', 'fifa', '21', 'preorder', 'fifa', '21', 'release', 'date', 'fifa', '21', 'ultimate', 'team', 'trailer', 'fifa', '21', 'ultimate', 'team', 'fut', '21', 'fifa', '21', 'ultimate', 'team', 'news', 'fut', '21', 'news', 'fut', '21', 'pack', 'opening', 'fifa', '21', 'ultimate', 'team', 'features', 'fut', '21', 'features', 'fut', '21', 'coop', 'fut', 'stadium', 'fut', '21', 'stadium', 'fifa', '21', 'gameplay', 'trailer', 'fifa', '21', 'ps5', 'fifa', 'fifa', '20', 'fifa', '21', 'career', 'mode']]

In [189]:
# Specify the file path
file_path = "category20.txt"

# Open the file in write mode
with open(file_path, "w") as file:
    # Iterate through the list of lists
    for sublist in big_list_of_tokenized_tags_20:
        # Convert each element to a string and join them with a delimiter (e.g., comma)
        line = ",".join(map(str, sublist))

        # Write the line to the file
        file.write(line + "\n")

In [190]:
df_category_24.head()

    categoryId                                     tokenized_tags
1           24  jacksepticeye funny funny meme memes jacksepti...
3           24  professor injury professor achilles professor ...
4           24  surprising dad father papa with dream car truc...
8           24  kylie jenner kendall jenner cardi b wap reacts...
10          24  faze rug rug rugfaze fazerug hide n seek hide ...

In [191]:
# Create a big list containing lists of tokens from each row in 'tokenized_tags' for category 24
big_list_of_tokenized_tags_24 = [
    row.split(" ") for row in df_category_24["tokenized_tags"]
]

# Print the big list
print(big_list_of_tokenized_tags_24[:3])

[['jacksepticeye', 'funny', 'funny', 'meme', 'memes', 'jacksepticeye', 'memes', 'reddit', 'subreddit', 'community', 'community', 'memes', 'community', 'subreddit', 'jacksepticeye', 'subreddit', 'reddit', 'memes', 'fan', 'submitted', 'spicy', 'memes', 'funny', 'pics', 'reaction', 'react', 'green', 'screen', 'funny', 'memes', 'funny', 'green', 'screen', 'dank', 'memes', 'memes', 'compilation', 'try', 'not', 'to', 'laugh', 'meme', 'fresh', 'memes', 'meme', 'review', 'funny', 'moments', 'bell', 'memes', 'bell', 'of', 'meme', 'jacksepticeye', 'bell'], ['professor', 'injury', 'professor', 'achilles', 'professor', '1v1', 'professor', 'live', 'professor', 'live', 'injury', 'professorlive', 'injury'], ['surprising', 'dad', 'father', 'papa', 'with', 'dream', 'car', 'truck', 'troca', 'camioneta', 'surprise', 'surprising', 'my', 'dad', 'parents', 'mom', 'mexican', 'latino', 'latinos', 'spanish', 'espanol', 'dream', 'truck', 'dream', 'car', 'goals', 'accomplish', 'car', 'tour', 'tour', 'chevrolet', '2020', 'new', 'new', 'chevrolet', 'interior', 'vlog', 'money', 'price', 'louie', 'castro', 'louie', 'castro', 'louies', 'life', 'the', 'baddest', 'perra', 'spanglish', 'louies', 'family', 'castro', 'sisters', 'mua', 'makeup', 'surprising', 'my', 'mom']]

In [192]:
# Specify the file path
file_path = "category24.txt"

# Open the file in write mode
with open(file_path, "w") as file:
    # Iterate through the list of lists
    for sublist in big_list_of_tokenized_tags_24:
        # Convert each element to a string and join them with a delimiter (e.g., comma)
        line = ",".join(map(str, sublist))

        # Write the line to the file
        file.write(line + "\n")